### ISSUE TITLE
[1.8.9] Interference with another mod.

### ISSUE THREAD

**Issue by blockbreaker1361** [sokratis12GR/ArmorPlus#12]
When I have your mod installed with Inventory pets and I have the Cloud Pet in my inventory, which gives creative flight, it causes the flight to no longer work. When I take your mod out, flight can be obtained. Armor Plus is the only extra mod I have added and then removed. No crash happened. I'm on Minecraft 1.8.9.

**Comment by sokratis12GR** [comment]
The Issue is on the GlobalEventsArmorPlus.java
I have set it so It doesn't allow other mods to have flight ability. But this can be changes/disabled at the config file armorplus.cfg . You have to make Enable Flight Ability = true to = false. It will disable the flight ability of the armors in ArmorPlus and enable it for the other mods. BTW working on making it work without the need of the config file, it will just take some time.

**Comment by blockbreaker1361** [comment]
OK. I'll adjust the config right away. Thank you for the quick response. :)

**Comment by sironin** [comment]
... Should be reopened as this issue still exists.  Unless it is actually intended to disable all other mods' flight options when yours is enabled.  Of those I've tested, interferes with slurpie dongles' topaz armor, ebon arts' celestial armor, and baublestuff's flying belt upgrade.

**Comment by sironin** [comment]
So apparently the way to properly implement armor based flight is to check when armor is equipped rather than every player tick.  Doing it every tick is what's disabling other mod flight.

**Comment by sokratis12GR** [comment]
It is intended to disable the other mod's flight ability.

**Comment by sokratis12GR** [comment]
FIXED In the 1.11.0 Update
