### ISSUE TITLE
[1.12.2] Vanilla Recipe Book Integration Issues

### ISSUE THREAD

**Issue by wise-io** [sokratis12GR/ArmorPlus#184]
There are some issues with ArmorPlus' integration with the Minecraft Recipe book in 1.12.2.

If I search for "chicken", I'd expect to see chicken armor in the list of results. Instead of chicken armor, I see 1 result from ArmorPlus that shows EVERY piece of armor it adds, not just the chicken armor. 

Can this be changed so that it shows 4 results ( 1 for the helmet, chestplate, leggings, and boots respectively), and doesn't show the other ArmorPlus armors that have nothing to do with chickens?

**Comment by sokratis12GR** [comment]
Thanks for reporting this issue, I personally didn't know that there was a recipe book integration in the first place, but it might be because of the armor grouping for the armors. Will see what I can do and add `type` specific groups. Additionally if you wish, we could continue our conversation about this feature/bug and/or other features/issues on our [Discord Server](https://discord.gg/ZVwmqyx)
