### ISSUE TITLE
[1.11] Can only craft decorative blocks, chainmail, and a book I cannot read. 

### ISSUE THREAD

**Issue by AndaleTheGreat** [sokratis12GR/ArmorPlus#81]
Lava Crystal Blocks do spawn correctly and the mod stays because it is our main fuel source. :) (I feel like they could use a lower spawn rate tho but maybe there are other uses I cannot find for them.)

- Curse Profile Export - https://files-na.curseapp.net/543d90ae-0ded-40c0-b8b6-44893dc97ad2/Forge_111-10.zip
- List of mods with versions [image] - http://i.imgur.com/MyZ0rAQ.png
- Video Example - https://drive.google.com/file/d/0B-zCPBgxfnQUaVVNb0c1aEpVVnM/view?usp=drivesdk
- Forge 10.19.0.2180

**Comment by sokratis12GR** [comment]
You can craft all the things properly, just that there isn't an jei support yet
And you still can't read the books because they are still wip
1.1-9.1.1.2-beta s a fully functional version for all the recipes and such, but I released it as beta because I'm still planning on doing changes on things like armor effects, recipes and such.

**Comment by AndaleTheGreat** [comment]
I should have also included in the video that I attempted to place the items according to the wiki and could not build anything that way either.

**Comment by sokratis12GR** [comment]
Uh, I want to apologize but the wiki is very outdated.

**Comment by sokratis12GR** [comment]
actually #82 leads to this so I label it as a bug.

**Comment by sokratis12GR** [comment]
Fixed in [armorplus-1.11-9.2.0.1-beta](https://minecraft.curseforge.com/projects/armorplus/files/2359042)
